# Generated by Django 3.0.6 on 2020-05-19 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='language', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('summary', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(default='images/0.jpg', upload_to='images/')),
                ('personal_image', models.ImageField(default='images/0.jpg', upload_to='images/')),
                ('candidate_name', models.CharField(default='Lee', max_length=20)),
                ('short_summary', models.CharField(default='Im a software engineer', max_length=200)),
                ('summary', models.CharField(default='Im a software engineer', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='language', max_length=20)),
                ('skill_name', models.CharField(default='swift', max_length=20)),
                ('percentage', models.CharField(default='80', max_length=20)),
            ],
        ),
    ]
