# Generated by Django 3.0.6 on 2020-05-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20200520_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_image', models.ImageField(default='images/0.jpg', upload_to='images/')),
                ('company_name', models.CharField(default='fudi', max_length=50)),
                ('ex_description', models.CharField(default='fudi', max_length=500)),
                ('date', models.DateField()),
            ],
        ),
    ]
