# Generated by Django 3.0.6 on 2020-05-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='position',
            field=models.CharField(default='left', max_length=5),
        ),
    ]
