# Generated by Django 3.0.6 on 2020-05-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_experience_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_image', models.ImageField(default='images/0.jpg', upload_to='images/')),
                ('code_name', models.CharField(default='fudi', max_length=50)),
                ('code_description', models.CharField(default='fudi', max_length=500)),
            ],
        ),
    ]
