# Generated by Django 3.0.6 on 2020-05-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='codes',
            name='code_url',
            field=models.CharField(default='fudi', max_length=500),
        ),
    ]
