# Generated by Django 3.0.6 on 2020-05-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_codes_code_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='works',
            old_name='name',
            new_name='work_image_name',
        ),
        migrations.RenameField(
            model_name='works',
            old_name='type',
            new_name='work_type',
        ),
        migrations.AddField(
            model_name='codes',
            name='code_image_name',
            field=models.CharField(default='fudi', max_length=50),
        ),
        migrations.AddField(
            model_name='person',
            name='main_image_name',
            field=models.CharField(default='Lee', max_length=20),
        ),
        migrations.AddField(
            model_name='person',
            name='personal_image_name',
            field=models.CharField(default='Lee', max_length=20),
        ),
        migrations.AddField(
            model_name='works',
            name='work_name',
            field=models.CharField(default='fudi', max_length=50),
        ),
    ]
