# Generated by Django 3.0.6 on 2020-05-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_auto_20200524_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='summary',
            field=models.TextField(default='Im a software engineer', max_length=1000),
        ),
        migrations.AlterField(
            model_name='works',
            name='work_name',
            field=models.CharField(default='work sample', max_length=50),
        ),
    ]
