# Generated by Django 3.0.6 on 2020-05-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_auto_20200525_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='ex_description',
            new_name='experience_description',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='ex_image',
            new_name='experience_image',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='position',
            new_name='job_position',
        ),
        migrations.AddField(
            model_name='works',
            name='work_url',
            field=models.CharField(default='https://medium.com/@lee5187415', max_length=500),
        ),
    ]
