# Generated by Django 3.0.6 on 2020-05-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_auto_20200527_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='work_image_url',
            field=models.CharField(default='https://miro.medium.com/fit/c/256/256/1*HD1OpqerWv8wo91EEoIIYA.jpeg', max_length=500),
        ),
    ]
