# Generated by Django 3.0.7 on 2020-07-03 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_works_work_image_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job',
            new_name='Project',
        ),
    ]
