# Generated by Django 3.0.7 on 2020-07-03 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_auto_20200703_1804'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
    ]
