# Generated by Django 3.0.7 on 2020-07-04 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_auto_20200703_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(default='Lee', max_length=500)),
                ('summary', models.CharField(max_length=200)),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='job.Project')),
            ],
        ),
    ]
