# Generated by Django 3.0.8 on 2020-07-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0017_auto_20200704_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='main_image',
            field=models.ImageField(default='job/static/images/0.jpg', upload_to='job/static/images/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='personal_image',
            field=models.ImageField(default='job/static/images/0.jpg', upload_to='job/static/images/'),
        ),
    ]
