# Generated by Django 3.0.8 on 2020-07-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0019_auto_20200704_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='main_image',
            field=models.ImageField(default='img/0.jpg', upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='personal_image',
            field=models.ImageField(default='img/0.jpg', upload_to='img/'),
        ),
    ]
