# Generated by Django 3.0.8 on 2020-07-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0024_auto_20200704_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimage',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='projectimage',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='projectimage',
            name='video_link',
        ),
        migrations.AddField(
            model_name='project',
            name='main_image',
            field=models.ImageField(default='img/0.jpg', upload_to='img/'),
        ),
        migrations.AddField(
            model_name='project',
            name='video_link',
            field=models.CharField(default='Lee', max_length=50),
        ),
    ]
