# Generated by Django 3.0.8 on 2020-07-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0026_auto_20200704_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='summary',
            field=models.TextField(max_length=1000),
        ),
    ]
