# Generated by Django 3.0.8 on 2020-07-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0027_auto_20200705_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='store_link',
            field=models.CharField(default='Lee', max_length=100),
        ),
    ]
