# Generated by Django 3.0.8 on 2020-07-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0028_project_store_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_screen',
            field=models.BooleanField(default=True),
        ),
    ]
