# Generated by Django 3.0.8 on 2020-08-08 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0031_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
